<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('breeds', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->foreignId('breed_group_id');
            $table->timestamps();
        });

        DB::table('breeds')->insert([
            ['name' => 'AUSZTRÁLIAI JUHÁSZKUTYA', 'breed_group_id' => 1],
            ['name' => 'BEARDED COLLIE', 'breed_group_id' => 1],
            ['name' => 'BELGA JUHÁSZKUTYA, GROENENDAEL', 'breed_group_id' => 1],
            ['name' => 'BELGA JUHÁSZKUTYA, MALINOIS', 'breed_group_id' => 1],
            ['name' => 'BELGA JUHÁSZKUTYA, TERVUEREN', 'breed_group_id' => 1],
            ['name' => 'BERGAMASCO', 'breed_group_id' => 1],
            ['name' => 'BERGER DE BEAUCE', 'breed_group_id' => 1],
            ['name' => 'BERGER DE BRIE', 'breed_group_id' => 1],
            ['name' => 'BERGER DE PICARDE', 'breed_group_id' => 1],
            ['name' => 'BERGER DE PYRENÉES', 'breed_group_id' => 1],
            ['name' => 'BOBTAIL', 'breed_group_id' => 1],
            ['name' => 'BORDER COLLIE', 'breed_group_id' => 1],
            ['name' => 'COLLIE, hosszúszőrű', 'breed_group_id' => 1],
            ['name' => 'COLLIE, rövidszőrű', 'breed_group_id' => 1],
            ['name' => 'CSEH FARKASKUTYA', 'breed_group_id' => 1],
            ['name' => 'DÉLOROSZ JUHÁSZKUTYA', 'breed_group_id' => 1],
            ['name' => 'FLANDRIAI BOUVIER', 'breed_group_id' => 1],
            ['name' => 'KOMONDOR', 'breed_group_id' => 1],
            ['name' => 'KUVASZ', 'breed_group_id' => 1],
            ['name' => 'LENGYEL ALFÖLDI JUHÁSZKUTYA', 'breed_group_id' => 1],
            ['name' => 'LENGYEL HEGYI KUTYA', 'breed_group_id' => 1],
            ['name' => 'MAREMMANO', 'breed_group_id' => 1],
            ['name' => 'MINIATURE AMERICAN SHEPHERD', 'breed_group_id' => 1],
            ['name' => 'MUDI', 'breed_group_id' => 1],
            ['name' => 'NÉMET JUHÁSZKUTYA normál', 'breed_group_id' => 1],
            ['name' => 'NÉMET JUHÁSZKUTYA hosszúszőrű', 'breed_group_id' => 1],
            ['name' => 'PULI, fehér', 'breed_group_id' => 1],
            ['name' => 'PULI, fekete', 'breed_group_id' => 1],
            ['name' => 'PULI, maszkos fakó', 'breed_group_id' => 1],
            ['name' => 'PULI, szürke', 'breed_group_id' => 1],
            ['name' => 'SCHAPENDOES', 'breed_group_id' => 1],
            ['name' => 'SCHIPPERKE', 'breed_group_id' => 1],
            ['name' => 'SHELTIE', 'breed_group_id' => 1],
            ['name' => 'SVÁJCI FEHÉR JUHÁSZKUTYA', 'breed_group_id' => 1],
            ['name' => 'WELSH CORGI, CARDIGAN', 'breed_group_id' => 1],
            ['name' => 'WELSH CORGI, PEMBROKE', 'breed_group_id' => 1],
            
            ['name' => 'AFFENPINSCHER', 'breed_group_id' => 2],
            ['name' => 'AIDI', 'breed_group_id' => 2],
            ['name' => 'ANGOL BULLDOG', 'breed_group_id' => 2],
            ['name' => 'ANGOL MASZTIFF', 'breed_group_id' => 2],
            ['name' => 'APPENZELLNER', 'breed_group_id' => 2],
            ['name' => 'ARGENTIN DOG', 'breed_group_id' => 2],
            ['name' => 'BERNI PÁSZTORKUTYA', 'breed_group_id' => 2],
            ['name' => 'BORDEAUX-I DOG', 'breed_group_id' => 2],
            ['name' => 'BOXER, csíkos', 'breed_group_id' => 2],
            ['name' => 'BOXER, sárga', 'breed_group_id' => 2],
            ['name' => 'BULLMASZTIFF', 'breed_group_id' => 2],
            ['name' => 'CANE CORSO', 'breed_group_id' => 2],
            ['name' => 'DOBERMANN, barna', 'breed_group_id' => 2],
            ['name' => 'DOBERMANN, Fekete-cser', 'breed_group_id' => 2],
            ['name' => 'FILA BRASILEIRO', 'breed_group_id' => 2],
            ['name' => 'HOVAWART', 'breed_group_id' => 2],
            ['name' => 'KAUKÁZUSI JUHÁSZKUTYA', 'breed_group_id' => 2],
            ['name' => 'KÖZÉP-ÁZSIAI JUHÁSZKUTYA', 'breed_group_id' => 2],
            ['name' => 'LANDSEER', 'breed_group_id' => 2],
            ['name' => 'LEONBERGER', 'breed_group_id' => 2],
            ['name' => 'MOSZKVAI ŐRKUTYA', 'breed_group_id' => 2],
            ['name' => 'MAJORCA MASTIFF', 'breed_group_id' => 2],
            ['name' => 'MASTINO NAPOLETANO', 'breed_group_id' => 2],
            ['name' => 'NÉMET DOG, csíkos', 'breed_group_id' => 2],
            ['name' => 'NÉMET DOG, fekete', 'breed_group_id' => 2],
            ['name' => 'NÉMET DOG, foltos', 'breed_group_id' => 2],
            ['name' => 'NÉMET DOG, kék', 'breed_group_id' => 2],
            ['name' => 'NÉMET DOG, sárga', 'breed_group_id' => 2],
            ['name' => 'NÉMET PINSCHER', 'breed_group_id' => 2],
            ['name' => 'NÉMET PINSCHER, TÖRPE', 'breed_group_id' => 2],
            ['name' => 'OROSZ FEKETE TERRIER', 'breed_group_id' => 2],
            ['name' => 'OSZTRÁK PINSCHER', 'breed_group_id' => 2],
            ['name' => 'PIRENEUSI HEGYIKUTYA', 'breed_group_id' => 2],
            ['name' => 'ROTTWEILER', 'breed_group_id' => 2],
            ['name' => 'SARPLANINAC', 'breed_group_id' => 2],
            ['name' => 'SCHNAUZER, ÓRIÁS, fekete', 'breed_group_id' => 2],
            ['name' => 'SCHNAUZER, ÓRIÁS, só-bors', 'breed_group_id' => 2],
            ['name' => 'SCHNAUZER, STANDARD, fekete', 'breed_group_id' => 2],
            ['name' => 'SCHNAUZER, STANDARD, só-bors', 'breed_group_id' => 2],
            ['name' => 'SCHNAUZER, TÖRPE, fehér', 'breed_group_id' => 2],
            ['name' => 'SCHNAUZER, TÖRPE, fekete', 'breed_group_id' => 2],
            ['name' => 'SCHNAUZER, TÖRPE, fekete-ezüst', 'breed_group_id' => 2],
            ['name' => 'SCHNAUZER, TÖRPE, só-bors', 'breed_group_id' => 2],
            ['name' => 'SHAR-PEI', 'breed_group_id' => 2],
            ['name' => 'SZENT BERNÁTHEGYI, hosszúszőrű', 'breed_group_id' => 2],
            ['name' => 'SZENT BERNÁTHEGYI, rövidszőrű', 'breed_group_id' => 2],
            ['name' => 'TIBETI MASZTIFF', 'breed_group_id' => 2],
            ['name' => 'ÚJFUNDLANDI', 'breed_group_id' => 2],

            ['name' => 'AIREDALE TERRIER', 'breed_group_id' => 3],
            ['name' => 'AMERIKAI STAFFORDSHIRE TERRIER', 'breed_group_id' => 3],
            ['name' => 'ANGOL BULLTERRIER', 'breed_group_id' => 3],
            ['name' => 'ANGOL BULLTERRIER-MINIATŰR', 'breed_group_id' => 3],
            ['name' => 'ANGOL STAFFORDSHIRE BULL TERRIER', 'breed_group_id' => 3],
            ['name' => 'ANGOL TOY TERRIER', 'breed_group_id' => 3],
            ['name' => 'AUSZTRÁL TERRIER', 'breed_group_id' => 3],
            ['name' => 'BEDLINGTON TERRIER', 'breed_group_id' => 3],
            ['name' => 'BORDER TERRIER', 'breed_group_id' => 3],
            ['name' => 'CAIRN TERRIER', 'breed_group_id' => 3],
            ['name' => 'CESKY TERRIER', 'breed_group_id' => 3],
            ['name' => 'DANDIE DIAMOND TERRIER', 'breed_group_id' => 3],
            ['name' => 'FOXTERRIER, drótszőrű', 'breed_group_id' => 3],
            ['name' => 'FOXTERRIER, simaszőrű', 'breed_group_id' => 3],
            ['name' => 'GLEN OF IMMALE TERRIER', 'breed_group_id' => 3],
            ['name' => 'ÍR TERRIER', 'breed_group_id' => 3],
            ['name' => 'JACK RUSSEL TERRIER SIMASZŐRŰ', 'breed_group_id' => 3],
            ['name' => 'JACK RUSSEL TERRIER SZÁLKÁSSZŐRŰ', 'breed_group_id' => 3],
            ['name' => 'JAPÁN TERRIER', 'breed_group_id' => 3],
            ['name' => 'KERRY-BLUE TERRIER', 'breed_group_id' => 3],
            ['name' => 'LAKELAND TERRIER', 'breed_group_id' => 3],
            ['name' => 'MANCHESTER TERRIER', 'breed_group_id' => 3],
            ['name' => 'NÉMET JAGDTERRIER', 'breed_group_id' => 3],
            ['name' => 'NORFOLK TERRIER', 'breed_group_id' => 3],
            ['name' => 'NORWICH TERRIER', 'breed_group_id' => 3],
            ['name' => 'PARSON RUSSELL TERRIER', 'breed_group_id' => 3],
            ['name' => 'SEALYHAM TERRIER', 'breed_group_id' => 3],
            ['name' => 'SILKY TERRIER', 'breed_group_id' => 3],
            ['name' => 'SKÓT TERRIER', 'breed_group_id' => 3],
            ['name' => 'SKYE TERRIER', 'breed_group_id' => 3],
            ['name' => 'SOFT COATED WHEATEN TERRIER', 'breed_group_id' => 3],
            ['name' => 'WELSH TERRIER', 'breed_group_id' => 3],
            ['name' => 'WEST HIGHLAND WHITE TERRIER', 'breed_group_id' => 3],
            ['name' => 'YORKSHIRE TERRIER', 'breed_group_id' => 3],

            ['name' => 'TACSKÓ, KANINCHEN, hosszúszőrű', 'breed_group_id' => 4],
            ['name' => 'TACSKÓ, KANINCHEN, rövidszőrű', 'breed_group_id' => 4],
            ['name' => 'TACSKÓ, KANINCHEN, szálkásszőrű', 'breed_group_id' => 4],
            ['name' => 'TACSKÓ, STANDARD, szálkásszőrű', 'breed_group_id' => 4],
            ['name' => 'TACSKÓ, STANDARD, hosszúszőrű', 'breed_group_id' => 4],
            ['name' => 'TACSKÓ, STANDARD, rövidszőrű', 'breed_group_id' => 4],
            ['name' => 'TACSKÓ, TÖRPE, hosszúszőrű', 'breed_group_id' => 4],
            ['name' => 'TACSKÓ, TÖRPE, rövidszőrű', 'breed_group_id' => 4],
            ['name' => 'TACSKÓ, TÖRPE, szálkásszőrű', 'breed_group_id' => 4],

            ['name' => 'AKITA INU', 'breed_group_id' => 5],
            ['name' => 'ALASZKAI MALAMUT', 'breed_group_id' => 5],
            ['name' => 'AMERIKAI AKITA', 'breed_group_id' => 5],
            ['name' => 'BASENJI', 'breed_group_id' => 5],
            ['name' => 'CHOW-CHOW, HOSSZÚSZŐRŰ, fahéj', 'breed_group_id' => 5],
            ['name' => 'CHOW-CHOW, HOSSZÚSZŐRŰ, fekete', 'breed_group_id' => 5],
            ['name' => 'CHOW-CHOW, HOSSZÚSZŐRŰ, kék', 'breed_group_id' => 5],
            ['name' => 'CHOW-CHOW, HOSSZÚSZŐRŰ, krém', 'breed_group_id' => 5],
            ['name' => 'CHOW-CHOW, HOSSZÚSZŐRŰ, vörös', 'breed_group_id' => 5],
            ['name' => 'CHOW-CHOW, RÖVIDSZŐRŰ, fahéj', 'breed_group_id' => 5],
            ['name' => 'CHOW-CHOW, RÖVIDSZŐRŰ, fekete', 'breed_group_id' => 5],
            ['name' => 'CHOW-CHOW, RÖVIDSZŐRŰ, kék', 'breed_group_id' => 5],
            ['name' => 'CHOW-CHOW, RÖVIDSZŐRŰ, krém', 'breed_group_id' => 5],
            ['name' => 'CHOW-CHOW, RÖVIDSZŐRŰ, vörös', 'breed_group_id' => 5],
            ['name' => "Cirneco dell'Etna", 'breed_group_id' => 5],
            ['name' => 'EURASIER', 'breed_group_id' => 5],
            ['name' => 'FÁRAÓKUTYA', 'breed_group_id' => 5],
            ['name' => 'FINN SPITZ', 'breed_group_id' => 5],
            ['name' => 'GRÖNLANDI KUTYA', 'breed_group_id' => 5],
            ['name' => 'HOKKAIDÓ', 'breed_group_id' => 5],
            ['name' => 'IZLANDI JUHÁSZKUTYA', 'breed_group_id' => 5],
            ['name' => 'JAPÁN SPITZ', 'breed_group_id' => 5],
            ['name' => 'JÄMTHUND', 'breed_group_id' => 5],
            ['name' => 'KAI', 'breed_group_id' => 5],
            ['name' => 'KÁNAÁNKUTYA', 'breed_group_id' => 5],
            ['name' => 'KARÉLIAI MEDVEKUTYA', 'breed_group_id' => 5],
            ['name' => 'KEESHOND', 'breed_group_id' => 5],
            ['name' => 'KOREAI JINDO KUTYA', 'breed_group_id' => 5],
            ['name' => 'LAJKA', 'breed_group_id' => 5],
            ['name' => 'LAPP PÁSZTORKUTYA', 'breed_group_id' => 5],
            ['name' => 'LAPPKUTYA', 'breed_group_id' => 5],
            ['name' => 'LUNDEHUND', 'breed_group_id' => 5],
            ['name' => 'NORVÉG BUHUND', 'breed_group_id' => 5],
            ['name' => 'NORVÉG ELKHOUND', 'breed_group_id' => 5],
            ['name' => 'NÉMET KIS SPITZ', 'breed_group_id' => 5],
            ['name' => 'NÉMET KÖZÉP SPITZ', 'breed_group_id' => 5],
            ['name' => 'NÉMET NAGY SPITZ', 'breed_group_id' => 5],
            ['name' => 'PERUI SZŐRTELEN KUTYA', 'breed_group_id' => 5],
            ['name' => 'PHARAOH HOUND', 'breed_group_id' => 5],
            ['name' => 'PODENCO CANARIO', 'breed_group_id' => 5],
            ['name' => 'PODENCO IBICENCO', 'breed_group_id' => 5],
            ['name' => 'POMERÁNIAI', 'breed_group_id' => 5],
            ['name' => 'SAMOYEDE', 'breed_group_id' => 5],
            ['name' => 'SHIBA INU', 'breed_group_id' => 5],
            ['name' => 'SHIKOKU', 'breed_group_id' => 5],
            ['name' => 'SZIBÉRIAI HUSKY', 'breed_group_id' => 5],
            ['name' => 'THAI BANGKAEW DOG', 'breed_group_id' => 5],
            ['name' => 'THAI RIDGEBACK', 'breed_group_id' => 5],
            ['name' => 'VOLPINO ITALIANO', 'breed_group_id' => 5],
            ['name' => 'WOLFSPITZ', 'breed_group_id' => 5],

            ['name' => 'AMERIKAI FOXHOUND', 'breed_group_id' => 6],
            ['name' => 'ANGOL FOXHOUND', 'breed_group_id' => 6],
            ['name' => 'BAJOR HEGYI VÉREB', 'breed_group_id' => 6],
            ['name' => 'BALKÁNI KOPÓ', 'breed_group_id' => 6],
            ['name' => 'BASSET BLEU DE GASCOGNE', 'breed_group_id' => 6],
            ['name' => 'BASSET HOUND', 'breed_group_id' => 6],
            ['name' => 'BEAGLE', 'breed_group_id' => 6],
            ['name' => 'BEAGLE HARRIER', 'breed_group_id' => 6],
            ['name' => 'BERNER LAUFHOUND', 'breed_group_id' => 6],
            ['name' => 'BERNI KISKOPÓ', 'breed_group_id' => 6],
            ['name' => 'BILLY', 'breed_group_id' => 6],
            ['name' => 'BIOODHOUND', 'breed_group_id' => 6],
            ['name' => 'BRANDLBRACKE', 'breed_group_id' => 6],
            ['name' => 'BLACK AND TAN COONHOUND', 'breed_group_id' => 6],
            ['name' => 'DALMATA', 'breed_group_id' => 6],
            ['name' => 'DREVER', 'breed_group_id' => 6],
            ['name' => 'DUNKER', 'breed_group_id' => 6],
            ['name' => 'ERDÉLYI KOPÓ', 'breed_group_id' => 6],
            ['name' => 'FRANCIA TRICOLOR KOPÓ', 'breed_group_id' => 6],
            ['name' => 'GRIFFON BLEU DE GASCOGNE', 'breed_group_id' => 6],
            ['name' => 'HAMILTON STÖVARE', 'breed_group_id' => 6],
            ['name' => 'HANNOVERI VÉREB', 'breed_group_id' => 6],
            ['name' => 'HARRIER', 'breed_group_id' => 6],
            ['name' => 'LUCERNI KISKOPÓ', 'breed_group_id' => 6],
            ['name' => 'NAGY ANGOL-FRANCIA TRICOLOR KOPÓ', 'breed_group_id' => 6],
            ['name' => 'OSZTRÁK RÖVIDSZŐRŰ VIZSLA', 'breed_group_id' => 6],
            ['name' => 'OTTERHOUND', 'breed_group_id' => 6],
            ['name' => 'PETIT BASSET GRIFFON VENDÉEN', 'breed_group_id' => 6],
            ['name' => 'PETIT BLUE DE GASCOGNE', 'breed_group_id' => 6],
            ['name' => 'PETIT GRIFFON BLEU DE GASCOGNE', 'breed_group_id' => 6],
            ['name' => 'PORCELAINE', 'breed_group_id' => 6],
            ['name' => 'RODÉZIAI RIDGEBACK', 'breed_group_id' => 6],
            ['name' => 'SCHWAYZER LAUFHOUND', 'breed_group_id' => 6],
            ['name' => 'SZLOVÁK KOPÓ', 'breed_group_id' => 6],

            ['name' => 'ANGOL SZETTER', 'breed_group_id' => 7],
            ['name' => 'BRETON SPÁNIEL', 'breed_group_id' => 7],
            ['name' => 'CESKY FOUSEK', 'breed_group_id' => 7],
            ['name' => 'CSEH VIZSLA, szálkásszőrű', 'breed_group_id' => 7],
            ['name' => 'DRÓTSZŐRŰ MAGYAR VIZSLA', 'breed_group_id' => 7],
            ['name' => 'EPAGNEUL BLEU PICARD', 'breed_group_id' => 7],
            ['name' => 'EPAGNEUL BRETON', 'breed_group_id' => 7],
            ['name' => 'GORDON SZETTER', 'breed_group_id' => 7],
            ['name' => 'GRIFFON drótszőrű', 'breed_group_id' => 7],
            ['name' => 'ÍR SETTER', 'breed_group_id' => 7],
            ['name' => 'KIS MÜNSTERLANDI VIZSLA', 'breed_group_id' => 7],
            ['name' => 'NAGY MÜNSTERLANDI VIZSLA', 'breed_group_id' => 7],
            ['name' => 'NÉMET VIZSLA, drótszőrű', 'breed_group_id' => 7],
            ['name' => 'NÉMET VIZSLA, hosszúszőrű', 'breed_group_id' => 7],
            ['name' => 'NÉMET VIZSLA, rövidszőrű', 'breed_group_id' => 7],
            ['name' => 'NÉMET VIZSLA, szálkás szőrű', 'breed_group_id' => 7],
            ['name' => 'SZLOVÁK DRÓTSZŐRŰ VIZSLA', 'breed_group_id' => 7],
            ['name' => 'OLASZ PINONE', 'breed_group_id' => 7],
            ['name' => 'OLASZ VIZSLA', 'breed_group_id' => 7],
            ['name' => 'POINTER', 'breed_group_id' => 7],
            ['name' => 'PUDELPOINTER', 'breed_group_id' => 7],
            ['name' => 'RÖVIDSZŐRŰ MAGYAR VIZSLA', 'breed_group_id' => 7],
            ['name' => 'WEIMARANER ', 'breed_group_id' => 7],

            ['name' => 'AMERIKAI COCKER SPÁNIEL', 'breed_group_id' => 8],
            ['name' => 'AMERIKAI VIZI SPÁNIEL', 'breed_group_id' => 8],
            ['name' => 'ANGOL COCKER SPÁNIEL', 'breed_group_id' => 8],
            ['name' => 'ANGOL SPRINGER SPÁNIEL', 'breed_group_id' => 8],
            ['name' => 'CURLY-COATED RETRIEVER', 'breed_group_id' => 8],
            ['name' => 'FLAT-COATED RETRIEVER', 'breed_group_id' => 8],
            ['name' => 'GOLDEN RETRIEVER', 'breed_group_id' => 8],
            ['name' => 'ÍR VIZI SPÁNIEL', 'breed_group_id' => 8],
            ['name' => 'KOOIKERHONDJE', 'breed_group_id' => 8],
            ['name' => 'LABRADOR RETRIEVER', 'breed_group_id' => 8],
            ['name' => 'LAGOTTO ROMAGNOLO', 'breed_group_id' => 8],
            ['name' => 'NÉMET FÜRJÉSZEB', 'breed_group_id' => 8],
            ['name' => 'SUSSAU SPÁNIEL', 'breed_group_id' => 8],
            ['name' => 'WELSH SPRINGER SPANIEL', 'breed_group_id' => 8],

            ['name' => 'BARBANCON', 'breed_group_id' => 9],
            ['name' => 'BELGA GRIFFON', 'breed_group_id' => 9],
            ['name' => 'BICHON FRISE', 'breed_group_id' => 9],
            ['name' => 'BICHON HAVANAIS', 'breed_group_id' => 9],
            ['name' => 'BOLOGNESE', 'breed_group_id' => 9],
            ['name' => 'BOSTON TERRIER', 'breed_group_id' => 9],
            ['name' => 'BROUXELI GRIFFON', 'breed_group_id' => 9],
            ['name' => 'CAVALIER KING CHARLES SPANIEL', 'breed_group_id' => 9],
            ['name' => 'CHIHUAHUA, hosszúszőrű', 'breed_group_id' => 9],
            ['name' => 'CHIHUAHUA, rövidszőrű', 'breed_group_id' => 9],
            ['name' => 'COTON DE TULAER', 'breed_group_id' => 9],
            ['name' => 'FRANCIA BULLDOG', 'breed_group_id' => 9],
            ['name' => 'JAPÁN CHIN', 'breed_group_id' => 9],
            ['name' => 'KÍNAI MEZTELEN KUTYA', 'breed_group_id' => 9],
            ['name' => 'KÍNAI MEZTELEN KUTYA (powder puff)', 'breed_group_id' => 9],
            ['name' => 'KING CHARLES SPENIEL', 'breed_group_id' => 9],
            ['name' => 'LHASA APSO', 'breed_group_id' => 9],
            ['name' => 'MÁLTAI SELYEMKUTYA', 'breed_group_id' => 9],
            ['name' => 'MOPS', 'breed_group_id' => 9],
            ['name' => 'PAPILLON', 'breed_group_id' => 9],
            ['name' => 'PEKINGI PALOTAKUTYA', 'breed_group_id' => 9],
            ['name' => 'PETIT CHIEN LION', 'breed_group_id' => 9],
            ['name' => 'RUSSIAN TOY LONG-HAIRED', 'breed_group_id' => 9],
            ['name' => 'RUSSIAN TOY SHORT-HAIRED', 'breed_group_id' => 9],
            ['name' => 'SHIH-TZU', 'breed_group_id' => 9],
            ['name' => 'TIBETI SPANIEL', 'breed_group_id' => 9],
            ['name' => 'TIBETI TERRIER', 'breed_group_id' => 9],
            ['name' => 'USZKÁR, KÖZÉP, fekete', 'breed_group_id' => 9],
            ['name' => 'USZKÁR, KÖZÉP, apricot', 'breed_group_id' => 9],
            ['name' => 'USZKÁR, KÖZÉP, FAWN', 'breed_group_id' => 9],
            ['name' => 'USZKÁR, KÖZÉP, barna', 'breed_group_id' => 9],
            ['name' => 'USZKÁR, KÖZÉP, ezüst', 'breed_group_id' => 9],
            ['name' => 'USZKÁR, KÖZÉP, fehér', 'breed_group_id' => 9],
            ['name' => 'USZKÁR, KÖZÉP, red', 'breed_group_id' => 9],
            ['name' => 'USZKÁR, ÓRIÁS, fekete', 'breed_group_id' => 9],
            ['name' => 'USZKÁR, ÓRIÁS, apricot', 'breed_group_id' => 9],
            ['name' => 'USZKÁR, ÓRIÁS, FAWN', 'breed_group_id' => 9],
            ['name' => 'USZKÁR, ÓRIÁS, barna', 'breed_group_id' => 9],
            ['name' => 'USZKÁR, ÓRIÁS, ezüst', 'breed_group_id' => 9],
            ['name' => 'USZKÁR, ÓRIÁS, fehér', 'breed_group_id' => 9],
            ['name' => 'USZKÁR, ÓRIÁS, red', 'breed_group_id' => 9],
            ['name' => 'USZKÁR, TÖRPE, fekete', 'breed_group_id' => 9],
            ['name' => 'USZKÁR, TÖRPE, apricot', 'breed_group_id' => 9],
            ['name' => 'USZKÁR, TÖRPE, FAWN', 'breed_group_id' => 9],
            ['name' => 'USZKÁR, TÖRPE, barna', 'breed_group_id' => 9],
            ['name' => 'USZKÁR, TÖRPE, ezüst', 'breed_group_id' => 9],
            ['name' => 'USZKÁR, TÖRPE, fehér', 'breed_group_id' => 9],
            ['name' => 'USZKÁR, TÖRPE, red', 'breed_group_id' => 9],
            ['name' => 'USZKÁR, TOY, fekete', 'breed_group_id' => 9],
            ['name' => 'USZKÁR, TOY, apricot', 'breed_group_id' => 9],
            ['name' => 'USZKÁR, TOY, FAWN', 'breed_group_id' => 9],
            ['name' => 'USZKÁR, TOY, barna', 'breed_group_id' => 9],
            ['name' => 'USZKÁR, TOY, ezüst', 'breed_group_id' => 9],
            ['name' => 'USZKÁR, TOY, fehér', 'breed_group_id' => 9],
            ['name' => 'USZKÁR, TOY, red', 'breed_group_id' => 9],

            ['name' => 'AFGÁN AGÁR', 'breed_group_id' => 10],
            ['name' => 'ANGOL AGÁR', 'breed_group_id' => 10],
            ['name' => 'AZAWAKH', 'breed_group_id' => 10],
            ['name' => 'BARZOJ', 'breed_group_id' => 10],
            ['name' => 'DEEHOUND', 'breed_group_id' => 10],
            ['name' => 'GALGO ESPAGNOL', 'breed_group_id' => 10],
            ['name' => 'ÍR FARKAS', 'breed_group_id' => 10],
            ['name' => 'MAGYAR AGÁR', 'breed_group_id' => 10],
            ['name' => 'OLASZ TÖRPE AGÁR', 'breed_group_id' => 10],
            ['name' => 'SALUKI', 'breed_group_id' => 10],
            ['name' => 'SLOUGHI', 'breed_group_id' => 10],
            ['name' => 'WHIPPET', 'breed_group_id' => 10],

            ['name' => 'FRANCIA BULLDOG  black&tan', 'breed_group_id' => 11],
            ['name' => 'FRANCIA BULLDOG blue&tan', 'breed_group_id' => 11],
            ['name' => 'FRANCIA BULLDOG csokoládé, csokoládé foltos', 'breed_group_id' => 11],
            ['name' => 'FRANCIA BULLDOG kék, kék foltos', 'breed_group_id' => 11],
            ['name' => 'FRANCIA BULLDOG lilac', 'breed_group_id' => 11],
            ['name' => 'FRANCIA BULLDOG lilac csíkos', 'breed_group_id' => 11],
            ['name' => 'FRANCIA BULLDOG sable', 'breed_group_id' => 11],
            ['name' => 'ALASZKAI KLEE KAI (mini husky)', 'breed_group_id' => 11],
            ['name' => 'AMERIKAI BULLDOG, bully', 'breed_group_id' => 11],
            ['name' => 'AMERIKAI BULLDOG, standard', 'breed_group_id' => 11],
            ['name' => 'ANGOL BULLDOG (El nem ismert szín)', 'breed_group_id' => 11],
            ['name' => 'CONTINENTAL BULLDOG', 'breed_group_id' => 11],
            ['name' => 'FRANCIA BULLDOG (egyéb színverzió)', 'breed_group_id' => 11],
            ['name' => 'FRANCIA BULLDOG merle', 'breed_group_id' => 11],
            ['name' => 'MINI BOULÉ', 'breed_group_id' => 11],
            ['name' => 'AMERICAN BULLY Classic', 'breed_group_id' => 11],
            ['name' => 'AMERICAN BULLY Extreme', 'breed_group_id' => 11],
            ['name' => 'AMERICAN BULLY Extreme Pocket', 'breed_group_id' => 11],
            ['name' => 'AMERICAN BULLY Pocket', 'breed_group_id' => 11],
            ['name' => 'AMERICAN BULLY Pocket Mikro', 'breed_group_id' => 11],
            ['name' => 'AMERICAN BULLY Standard', 'breed_group_id' => 11],
            ['name' => 'AMERICAN BULLY XL', 'breed_group_id' => 11],
            ['name' => 'AMERICAN BULLY XXL', 'breed_group_id' => 11],
            ['name' => 'AMERICAN EXOTIK BULLY', 'breed_group_id' => 11],
            ['name' => 'AMERIKAI PITBULL Terrier', 'breed_group_id' => 11],
            ['name' => 'SHORTY BULL', 'breed_group_id' => 11],
            ['name' => 'BOERBOEL', 'breed_group_id' => 11],
            ['name' => 'BOLONKA FRANZUSKA', 'breed_group_id' => 11],
            ['name' => 'BOLONKA ZWETNA', 'breed_group_id' => 11],
            ['name' => 'BOXER (el nem ismert színű)', 'breed_group_id' => 11],
            ['name' => 'BIEWER YORKSHIRE TERRIER  kék -fehér arany', 'breed_group_id' => 11],
            ['name' => 'BIEWER YORKSHIRE TERRIER fekete-fehér arany', 'breed_group_id' => 11],
            ['name' => 'BÍRÓ YORKSHIRE TERRIER chokolate', 'breed_group_id' => 11],
            ['name' => 'BÍRÓ YORKSHIRE TERRIER chokolate-weis gold', 'breed_group_id' => 11],
            ['name' => 'ADDA YORKSHIRE TERRIER', 'breed_group_id' => 11],
            ['name' => 'AMERIKAI MEZTELEN TERRIER', 'breed_group_id' => 11],
            ['name' => 'BIEWER YORKSHIRE TERRIER', 'breed_group_id' => 11],
            ['name' => 'BIRO YORKSHIRE TERRIER', 'breed_group_id' => 11],
            ['name' => 'BLACK YORKSHIRE TERRIER', 'breed_group_id' => 11],
            ['name' => 'BLUE DIAMOND BIEWER YORKSHIRE TERRIER', 'breed_group_id' => 11],
            ['name' => 'CHOKOLADE MERLE YORKSHIRE TERRIER', 'breed_group_id' => 11],
            ['name' => 'ÓCEÁN PEARL YORKSHIRE TERRIER', 'breed_group_id' => 11],
            ['name' => 'WHITE YORKSHIRE TERRIER', 'breed_group_id' => 11],
            ['name' => 'GOLLDUST YORKSHIRE TERRIER arany', 'breed_group_id' => 11],
            ['name' => 'GOLLDUST YORKSHIRE TERRIER arany-fehér', 'breed_group_id' => 11],
            ['name' => 'MERLE GOLDUST YORKSHIRE TERRIER', 'breed_group_id' => 11],
            ['name' => 'BLUE MERLE YORKSHIRE TERRIER', 'breed_group_id' => 11],
            ['name' => 'BLUE/BLACK & TAN YORKSHIRE TERRIE', 'breed_group_id' => 11],
            ['name' => 'CHOKOLADE YORKSHIRE TERRIER', 'breed_group_id' => 11],
            ['name' => 'GOLDDUST YORKSHIRE TERRIER', 'breed_group_id' => 11],
            ['name' => 'MERLE YORKSHIRE TERRIER (egyéb)', 'breed_group_id' => 11],
            ['name' => 'SABLE MERLE YORKSHIRE TERRIER', 'breed_group_id' => 11],
            ['name' => 'NÉMET JUHÁSZKUTYA black&silver hosszúszőrű', 'breed_group_id' => 11],
            ['name' => 'NÉMET JUHÁSZKUTYA black&silver normál', 'breed_group_id' => 11],
            ['name' => 'NÉMET JUHÁSZKUTYA blue sable hosszúszőrű', 'breed_group_id' => 11],
            ['name' => 'NÉMET JUHÁSZKUTYA blue sable normál', 'breed_group_id' => 11],
            ['name' => 'BANDOG TÖRZSKÖNYVEZETT PÉLDÁNYOK', 'breed_group_id' => 11],
            ['name' => 'BULGARIAN SHEPHERD DOG', 'breed_group_id' => 11],
            ['name' => 'CATAHOULA LEOPARD DOG', 'breed_group_id' => 11],
            ['name' => 'HOVAWART egyéb színek', 'breed_group_id' => 11],
            ['name' => 'KELET EUROPAI JUHÁSZ', 'breed_group_id' => 11],
            ['name' => 'MAGYAR SZELINDEK', 'breed_group_id' => 11],
            ['name' => 'MOSZKVAI ŐRKUTYA', 'breed_group_id' => 11],
            ['name' => 'NÉMET DOG (el nem ismert színek)', 'breed_group_id' => 11],
            ['name' => 'NÉMET JUHÁSZKUTYA kék-cser hosszúszőrű', 'breed_group_id' => 11],
            ['name' => 'NÉMET JUHÁSZKUTYA kék-cser rövidszőrű', 'breed_group_id' => 11],
            ['name' => 'NÉMET JUHÁSZKUTYA liver-colored hosszúszőrű', 'breed_group_id' => 11],
            ['name' => 'NÉMET JUHÁSZKUTYA liver-colored normál', 'breed_group_id' => 11],
            ['name' => 'OROSZ FEKETE TERRIER (el nem ismert színv.)', 'breed_group_id' => 11],
            ['name' => 'Pryter', 'breed_group_id' => 11],
            ['name' => 'PARTI VAGY FOLTOS USZKÁR, közép', 'breed_group_id' => 11],
            ['name' => 'PARTI VAGY FOLTOS USZKÁR, közép (BARNA)', 'breed_group_id' => 11],
            ['name' => 'PARTI VAGY FOLTOS USZKÁR, közép (EZÜST)', 'breed_group_id' => 11],
            ['name' => 'PARTI VAGY FOLTOS USZKÁR, közép (FAWN)', 'breed_group_id' => 11],
            ['name' => 'PARTI VAGY FOLTOS USZKÁR, közép (FEHÉR, L. CREAM)', 'breed_group_id' => 11],
            ['name' => 'PARTI VAGY FOLTOS USZKÁR, közép (FEKETE)', 'breed_group_id' => 11],
            ['name' => 'PARTI VAGY FOLTOS USZKÁR, közép (KÉK-BLUE)', 'breed_group_id' => 11],
            ['name' => 'PARTI VAGY FOLTOS USZKÁR, óriás (BARNA)', 'breed_group_id' => 11],
            ['name' => 'PARTI VAGY FOLTOS USZKÁR, óriás (EZÜST)', 'breed_group_id' => 11],
            ['name' => 'PARTI VAGY FOLTOS USZKÁR, óriás (FAWN)', 'breed_group_id' => 11],
            ['name' => 'PARTI VAGY FOLTOS USZKÁR, óriás (FEHÉR, L. CREAM)', 'breed_group_id' => 11],
            ['name' => 'PARTI VAGY FOLTOS USZKÁR, óriás (FEKETE)', 'breed_group_id' => 11],
            ['name' => 'PARTI VAGY FOLTOS USZKÁR, óriás (KÉK-BLUE)', 'breed_group_id' => 11],
            ['name' => 'PARTI VAGY FOLTOS USZKÁR, törpe', 'breed_group_id' => 11],
            ['name' => 'PARTI VAGY FOLTOS USZKÁR, törpe (BARNA)', 'breed_group_id' => 11],
            ['name' => 'PARTI VAGY FOLTOS USZKÁR, törpe (EZÜST)', 'breed_group_id' => 11],
            ['name' => 'PARTI VAGY FOLTOS USZKÁR, törpe (FAWN)', 'breed_group_id' => 11],
            ['name' => 'PARTI VAGY FOLTOS USZKÁR, törpe (FEHÉR, L. CREAM)', 'breed_group_id' => 11],
            ['name' => 'PARTI VAGY FOLTOS USZKÁR, törpe (FEKETE)', 'breed_group_id' => 11],
            ['name' => 'PARTI VAGY FOLTOS USZKÁR, törpe (KÉK-BLUE)', 'breed_group_id' => 11],
            ['name' => 'PARTI VAGY FOLTOS USZKÁR, toy', 'breed_group_id' => 11],
            ['name' => 'PARTI VAGY FOLTOS USZKÁR, toy (BARNA)', 'breed_group_id' => 11],
            ['name' => 'PARTI VAGY FOLTOS USZKÁR, toy (EZÜST)', 'breed_group_id' => 11],
            ['name' => 'PARTI VAGY FOLTOS USZKÁR, toy (FAWN)', 'breed_group_id' => 11],
            ['name' => 'PARTI VAGY FOLTOS USZKÁR, toy (FEHÉR, L. CREAM)', 'breed_group_id' => 11],
            ['name' => 'PARTI VAGY FOLTOS USZKÁR, toy (FEKETE)', 'breed_group_id' => 11],
            ['name' => 'PARTI VAGY FOLTOS USZKÁR, toy (KÉK-BLUE)', 'breed_group_id' => 11],
            ['name' => 'PHANTOM VAGY RAJZOS USZKÁR, óriás', 'breed_group_id' => 11],
            ['name' => 'PHANTOM VAGY RAJZOS USZKÁR, közép', 'breed_group_id' => 11],
            ['name' => 'PHANTOM VAGY RAJZOS USZKÁR, törpe', 'breed_group_id' => 11],
            ['name' => 'POMERANIAN CHOCOLATE AND TAN MERLE', 'breed_group_id' => 11],
            ['name' => 'POMERANIAN PARTI-COLOR', 'breed_group_id' => 11],
            ['name' => 'PHANTOM VAGY RAJZOS USZKÁR, toy', 'breed_group_id' => 11],
            ['name' => 'POMERANIAN', 'breed_group_id' => 11],
            ['name' => 'RUSSIAN TOY LONG-HAIRED', 'breed_group_id' => 11],
            ['name' => 'RUSSIAN TOY SHORTHAIR', 'breed_group_id' => 11],
            ['name' => 'Mame Shiba', 'breed_group_id' => 11],
            ['name' => 'MINIATURE AUSTRALIAN SHEPHERD', 'breed_group_id' => 11],
            ['name' => 'TOY AUSTRALIAN SHEPHERD', 'breed_group_id' => 11],
            ['name' => 'HOSSZÚ LÁBÚ SÁRGA ERDÉLYI KOPÓ', 'breed_group_id' => 11],
            ['name' => 'RÖVID LÁBÚ ERDÉLYI KOPÓ', 'breed_group_id' => 11],
            ['name' => 'SCHNAUZER, TÖRPE, particolor', 'breed_group_id' => 11],
            ['name' => 'SILKEN WINDHOUND', 'breed_group_id' => 11],
            ['name' => 'SINKA', 'breed_group_id' => 11],
            ['name' => 'SPANIEL, coboly', 'breed_group_id' => 11],
            ['name' => 'SPANIEL, csokoládé-coboly', 'breed_group_id' => 11],
            ['name' => 'TACSKÓ KANINCHEN PIEBALD hosszúszőrű', 'breed_group_id' => 11],
            ['name' => 'TACSKÓ KANINCHEN PIEBALD rövidszőrű', 'breed_group_id' => 11],
            ['name' => 'TACSKÓ, TÖRPE, PIEBALD hosszúszőrű', 'breed_group_id' => 11],
            ['name' => 'TACSKÓ, TÖRPE, PIEBALD rövidszőrű', 'breed_group_id' => 11],
            ['name' => 'TAJGAN', 'breed_group_id' => 11],
            ['name' => 'WHIPPET hosszú szőrű', 'breed_group_id' => 11],
            ['name' => 'WORKING PIT BULLDOG', 'breed_group_id' => 11],
            ['name' => 'EGYÉB', 'breed_group_id' => 11],
            ['name' => 'YAKUTIAN LAIKA', 'breed_group_id' => 11],
            ['name' => 'Pryter', 'breed_group_id' => 11],

            ['name' => 'Fajtanélküli', 'breed_group_id' => 12],



        ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('breeds');
    }
};
